name: Docker CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Docker image
        run: |
          docker build -t backend ./backend

      - name: Build Frontend Docker image
        run: |
          docker build -t frontend ./frontend
